[package]
name = "diogenes"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7"
num-derive = "0.4"
num-traits = "0.2"
rand = "0.8"
strum = "0.26"
strum_macros = "0.26"
